-record(request, {callback,
		  callback_parsed,
		  mode,
		  topic,
		  topic_parsed,
		  verify,
		  lease_seconds=0,
		  secret,
		  verify_token,
		  url=[]}).

-record(subscription, {topic,
		       topic_parsed,
		       callback,
		       callback_parsed,
		       lease_seconds=0,
		       secret,
		       created,
		       active=false,
		       verified=false}).
